name: Push to docker hub

on:
  release:
    types: [created]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        env:
          PUSH: ${{ env.PUSH }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/ddsb:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/ddsb:${{ github.event.release.tag_name }}